version: 2.1

orbs:
  golangci: ory/golangci@0.0.9

jobs:
  build:
    docker:
      - image: circleci/golang:1.15

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: make deps
      - run:
          name: Run lint
          command: |
            curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0
            make lint
      - run:
          name: Run tests
          command: make test
