version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.15

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: make deps
      - run:
          name: Run lint
          command: make lint
      - run:
          name: Run tests
          command: make test
